version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/angular-realworld-example-app/
hooks:
  AfterInstall:
   - location: setup.sh
     timeout: 600
     runas: root
  # ApplicationStart:
  #  - location: run.sh
  #    timeout: 300
  #    runas: root
